version: "3.0"

services:
  kitchenrp-server:
    build:
      dockerfile: ./docker/kitchen-rp-server/Dockerfile
      context: ../
  database:
    build:
      dockerfile: ./docker/database/Dockerfile
      context: ../
  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: ../
    ports:
      - 80:80

